### ISSUE TITLE
Text should be removed from documentation. 

### ISSUE THREAD

**Issue by Sid672** [Sid672/PBL#1]
These lines should be removed:
1) Heading: You have to run the code. 
2) Line below second step: This is the background image of main program.

**Comment by noturshek** [comment]
Hi @Sid672 ,

I would like to work on this issue. Could you please assign this issue to me after letting me know you want the above lines only to be removed or you want them to replace them with some another text.

Best,
Abhishek

**Comment by Sid672** [comment]
Hello Abhishek!  thanks for your interest on working on this issue. But I am really sorry you can't contribute to the project because it's a college project so only team members are allowed to solve this issue.

**Comment by noturshek** [comment]
OK, NP

**Comment by Sid672** [comment]
Issue is resolved

**Comment by Sid672** [comment]
Issue is resolved
